repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: inlets
  url: https://inlets.github.io/inlets-operator/
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: inlets
  namespace: inlets
  chart: inlets/inlets-operator
  version: ~0.7.6
  values:
  - values/inlets.yaml

- name: external-dns
  namespace: external-dns
  chart: bitnami/external-dns
  version: ~3.0.1
  values:
  - values/external-dns/values.yaml
  secrets:
  - values/external-dns/secrets.enc.yaml

- name: traefik
  namespace: traefik
  chart: stable/traefik
  version: ~1.86.2
  values:
  - values/traefik.yaml
  needs:
  - inlets/inlets
  - external-dns/external-dns
  
