repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: inlets
  url: https://inlets.github.io/inlets-operator/

releases:
- name: inlets
  namespace: inlets
  chart: inlets/inlets-operator
  version: ~0.7.6
  values:
  - provider: gce
    projectID: homelab-277422
    zone: us-central1-f
    clientImage: inlets/inlets:2.7.0

- name: traefik
  namespace: traefik
  chart: stable/traefik
  version: ~1.86.2
  values:
  - rbac:
      enabled: true
  needs:
  - inlets/inlets
